// REGISTRATION
export const REGISTRATION_START="REGISTRATION_START";
export const REGISTRATION_SUCCESS='REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED='REGISTRATION_FAILED';
export const CANCEL_REGISTRATION_STATUS='CANCEL_REGISTRATION_STATUS';


// VERIFICATION
export const VERIFICATION_START="VERIFICATION_START";
export const VERIFICATION_SUCCESS='VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED='VERIFICATION_FAILED';

// LOCAL DATA 
export const GET_USER_DATA ='GET_USER_DATA';