// REGISTRATION
export const SEND_MESSAGE="SEND_MESSAGE";

// CONTACT_USERS
export const GET_CONTACT_USERS_START='GET_CONTACT_USERS_START';
export const GET_CONTACT_USERS_SUCCESS='GET_CONTACT_USERS_SUCCESS';
export const GET_CONTACT_USERS_FAİLED='GET_CONTACT_USERS_FAİLED';

export const GET_CHAT_SCREEN_USER_DETAIL='GET_CHAT_SCREEN_USER_DETAIL';
export const GET_CHAT_SCREEN_USER_DETAIL_CANCEL='GET_CHAT_SCREEN_USER_DETAIL_CANCEL';